.PHONY: test
test:
	cd ./util && go test -gcflags "all=-N -l" ./...
	cd ./lib/logger && go test -gcflags "all=-N -l" ./...
	cd ./lib/http && go test -gcflags "all=-N -l" ./...
	cd ./lib/config && go test -gcflags "all=-N -l" ./...
	cd ./lib/concurrency && go test -gcflags "all=-N -l" ./...