[app]
name = "http-diff"

[log]
console = true
level = "INFO"
path = "./"
file_name = "http_diff.log"
max_size = 100
max_backups = 30
max_age = 15

[fast_http]
read_time_out = "500ms"
write_time_out = "500ms"
max_idle_conn_duration = "1h"
max_conns_per_host = 512
retry_times = 2

#[[diff_configs]]
#name = "task_1"
#concurrency = 1
#wait_time = "1000ms"
#work_dir = "./data"
#payload = "payload_task_1.txt"
#url_a = "http://127.0.0.1:8080/ping"
#url_b = "http://127.0.0.1:8080/ping"
#method = "GET"
#content_type = "application/json"
#ignore_fields = "traceId"
#output_show_no_diff_line = true
#log_statistics = true
#success_conditions = "code="

[[diff_configs]]
name = "task_2"
concurrency = 1
wait_time = "1000ms"
work_dir = "./data"
payload = "payload_task_2.txt"
url_a = "http://127.0.0.1:8080/form"
url_b = "http://127.0.0.1:8080/form"
method = "POST"
content_type = "application/x-www-form-urlencoded"
ignore_fields = "traceId"
output_show_no_diff_line = true
log_statistics = true
success_conditions = "code="

#[[diff_configs]]
#name = "task_8"
#concurrency = 8
#wait_time = "0ms"
#work_dir = "./data"
#payload = "payload_task_8.txt"
#url_a = "http://127.0.0.1:8080/ping"
#url_b = "http://127.0.0.1:8080/ping"
#method = "GET"
#content_type = "application/json"
#ignore_fields = "traceId"
#output_show_no_diff_line = true
#log_statistics = true
#success_conditions = "code="